applications/home/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path

from . import views

app_name = "home_app"

urlpatterns = [
    path('home/', views.HomePage.as_view(), name='iniciar_sesion'),
    path('mixin/', views.TemplatePruebaMixin.as_view(), name='mixin')
]

applications/users/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'users_app'



urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='registrar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('update/', views.UpdatePasswordView.as_view(), name='update'),
    path('verification/<pk>/', views.CodeVerificationView.as_view(), name='verification')
]

usuarios/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "user_app"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.users.urls')),
    path('', include('applications.home.urls')),
]

applications/home/models.py
from django.db import models

# Create your models here.

applications/home/views.py
import datetime

from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView

# Create your views here.

class FechaMixin(object):

    def get_context_data(self, **kwargs):
        context = super(FechaMixin, self).get_context_data(**kwargs)
        context['fecha'] = datetime.datetime.now()
        return context

class HomePage(LoginRequiredMixin, TemplateView):
    template_name = 'home/index.html'
    login_url = reverse_lazy('users_app:login')




class TemplatePruebaMixin(FechaMixin, TemplateView):
    template_name = 'home/mixin.html'        

templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Panel de usuario</h1>
    <h3>Bienvenido: {{user}}</h3>
    
    <ul>
        <li><a href="{% url 'users_app:logout' %}">Cerrar sesion</a></li>
        <li><a href="{% url 'users_app:update' %}">Actualizar datos</a></li>
    </ul> 
</body>
</html>

templates/home/mixin.html
<h1>Probando mixin</h1>

{{fecha}}